Update move events of Diagram Editor
DHTMLX/docs-diagram pull request #13
Opened 2023-12-22 14:45 UTC by mafanya23

2023-12-22 17:08 UTC, Sorokin-Oleg requested changes
@mafanya23 с большего все хорошо. Посмотри оставленные комментарии, они будут актуальны для всех указанных (аналогичных) событий

2023-12-22 17:08 UTC, Sorokin-Oleg commented on docs/api/diagram_editor/editor/events/aftergroupmove_event.md
> +    event: MouseEvent | PointerEvent,
@mafanya23 давай для событий указанных в задаче DHX-4352 уберем `MouseEvent` из типов. В типах тоже подправлю.

2024-01-08 13:29 UTC, mafanya23 commented on docs/api/diagram_editor/editor/events/afteritemmove_event.md
> +The event doesn't work with the **line** object
Я бы оставила. В гайдах у нас Lines описаны среди других items -https://docs.dhtmlx.com/diagram/guides/items_index/ю Поэтому, на мой взгляд, вопрос у пользователей может вполне закономерно возникать, почему для line не работает ивент. Может line, конечно, и не совсем верно отнесен к items, но наверное так получилось, потому что описывались все "элементы" диаграмм, и их решили не выносить отдельно..

2024-01-08 13:40 UTC, mafanya23 commented on docs/api/diagram_editor/editor/events/aftergroupmove_event.md
>  // attaching a handler to the event
Вроде всегда писали attach handler..) Но как оно правильнее? @serhiipylypchuk1991, что ты думаешь по этому поводу?

2024-01-10 10:20 UTC, Sorokin-Oleg requested changes
@mafanya23 к заметке есть вопросы, оставил описание к первому элементу(актуально для всех заметок). В остальном все верно.

2024-01-10 10:20 UTC, Sorokin-Oleg commented on docs/api/diagram_editor/editor/events/aftergroupmove_event.md
> +The event fires once for all groups/swimlanes being held and dragged. The ids of dragged elements are provided in the `batch` property of the callback function's parameter.
@mafanya23 скорее описание должно быть не таким. Это событие не один раз для всех сработает. А сработает на одном элементе (на target элементе), а не на всех. Собственно для этого и вводился `batch`.

2024-01-10 12:43 UTC, Sorokin-Oleg approved these changes

2024-01-22 11:32 UTC, mafanya23 commented on docs/api/diagram_editor/editor/events/aftershapeiconclick_event.md
Наверное, если мы везде убираем added in до версии 4.1, в after/beforeShapeIconClick тоже стоит убрать added in v3.1?

2024-02-01 09:43 UTC, merged