Toolbar API description
DHTMLX/docs-diagram pull request #14
Opened 2024-02-01 09:22 UTC by serhiipylypchuk1991

2024-03-14 09:57 UTC, Sorokin-Oleg requested changes
@serhiipylypchuk1991 посмотри комментарии. Лучше всего будет созвонится, и пройтись по ним.

2024-03-14 09:57 UTC, Sorokin-Oleg commented on docs/api/diagram_editor/toolbar/config/css_property.md
> +### Description
@serhiipylypchuk1991 нужна будет ссылка в описание. И краткая наводка на стилизацию css переменными

2024-03-14 09:57 UTC, Sorokin-Oleg commented on docs/api/diagram_editor/toolbar/config/items_property.md
> +sidebar_label: items!!
@serhiipylypchuk1991 данную страничку не проверял. Вижу, тут достаточно много информации опущено. Позже пообщаемся по ней отдельно.

2024-03-14 09:57 UTC, Sorokin-Oleg commented on docs/api/diagram_editor/toolbar/events/afterhide_event.md
> +"afterHide": ( events: Event ) => void;
@serhiipylypchuk1991 лишние отступы внутри скобочек

2024-03-14 09:57 UTC, Sorokin-Oleg commented on docs/api/diagram_editor/toolbar/events/inputcreated_event.md
> +---
@serhiipylypchuk1991 давай уберем это событие, в контексте редактора, оно будет мало полезным

2024-03-14 09:57 UTC, Sorokin-Oleg commented on docs/api/diagram_editor/toolbar/events/treecollection_events.md
> +---
@serhiipylypchuk1991 вот я бы точно также сделал для событий `Toolbar` suite. 
В suite могут быть изменения, и довольно часто эти изменения будут сразу актуальными и для редактора. Просто бы списком вынесли, и показали, как их слушать.

2024-03-14 09:57 UTC, Sorokin-Oleg commented on docs/api/diagram_editor/toolbar/events/treecollection_events.md
> +---
Вот кстати и тут, мог бы быть пример, как слушать эти события в рамках редактора диаграмм.

2024-03-14 09:57 UTC, Sorokin-Oleg commented on docs/api/diagram_editor/toolbar/events/treecollection_events.md
> +---
А уже есть такая `Toolbar events overview` ее просто дополнить, что эти события. События из suite. И было бы хорошо.

2024-03-14 09:57 UTC, Sorokin-Oleg commented on docs/api/diagram_editor/toolbar/methods/overview.md
> +| [loadItems()](https://docs.dhtmlx.com/suite/tree_collection/api/treecollection_loaditems_method.md) | Loads child items of a control from a file                 |
@serhiipylypchuk1991 не будет работать в diagram

2024-03-14 09:57 UTC, Sorokin-Oleg commented on docs/api/diagram_editor/toolbar/methods/overview.md
> +| [load()](https://docs.dhtmlx.com/suite/tree_collection/api/treecollection_load_method.md)         | Loads items from a file                                        |
@serhiipylypchuk1991 не будет работать в diagram

2024-03-14 09:57 UTC, Sorokin-Oleg commented on docs/api/diagram_editor/toolbar/methods/overview.md
> +---
@serhiipylypchuk1991 предложил бы аналогичную схему, как в events. Одна страница с сылками, и кратким гайдом, как этим пользоваться. Так как методы, события актуальные для suite, там обновляются, исправляются. И в редакторе они занимают не первое место. 
Единственное метод `parse`, вот он уже исключительно метод тулбара из редактора диаграмм.

2024-03-14 09:57 UTC, Sorokin-Oleg commented on docs/api/diagram_editor/toolbar/methods/overview.md
> +---
Опять таки все ошибки, будут кочевать из доки в доку. Лучше хранить их на местах. Если API не отличается.

2024-03-14 09:57 UTC, Sorokin-Oleg commented on docs/api/diagram_editor/toolbar/methods/parse_method.md
> +parse(items: array): void;
Один из примеров, когда паттерны suite вмешались в diagram
Должно быть так
```
parse(items: (object | string)[]): void;
```

2024-03-18 16:01 UTC, Sorokin-Oleg requested changes

2024-03-18 16:01 UTC, Sorokin-Oleg commented on docs/api/diagram_editor/toolbar/methods/unselect_method.md
> +---
@serhiipylypchuk1991 наверное забыл удалить

2024-03-18 16:01 UTC, Sorokin-Oleg commented on docs/guides/localization.md
> +    textProps: "Text style",
@serhiipylypchuk1991 не смотрел. Выделим в отдельную задачу

2024-03-19 08:40 UTC, Sorokin-Oleg requested changes

2024-03-19 08:40 UTC, Sorokin-Oleg commented on docs/api/diagram_editor/toolbar/events/overview.md
> +editor.toolbar.events.on("click", ($id, event) => {
@serhiipylypchuk1991 в качестве аргумента просто `id`. А уже то, что является значением аргумента идет с `$type` про это в задаче написано.

2024-03-19 08:40 UTC, Sorokin-Oleg commented on docs/api/diagram_editor/toolbar/events/toolbar_events.md
> +editor.toolbar.events.on("click", ($id, event) => {
@serhiipylypchuk1991 комментарий выше

2024-03-19 08:40 UTC, Sorokin-Oleg commented on docs/api/diagram_editor/toolbar/methods/overview.md
> +Use the [`parse()`](api/diagram_editor/toolbar/methods/parse_method.md) method to manipulate data in Toolbar. This method covers almost all common cases for working with Toolbar.
@serhiipylypchuk1991 примечание давай оставим, но уберем фразу про cases, так как тут без конкретики

2024-03-19 10:08 UTC, Sorokin-Oleg approved these changes

2024-03-19 13:07 UTC, mafanya23 commented on docs/api/diagram_editor/toolbar/methods/getstate_method.md
> +
Gets the value/state of a control in Toolbar

2024-03-19 13:08 UTC, mafanya23 commented on docs/api/diagram_editor/toolbar/methods/getstate_method.md
> +- `id` - (optional) an ID of Toolbar item. See the full list of available items [here](api/diagram_editor/toolbar/config/items_property.md)
the ID of a Toolbar item

2024-03-19 13:09 UTC, mafanya23 commented on docs/api/diagram_editor/toolbar/methods/getstate_method.md
> +// gets a state of a control by ID
the state of a control

2024-03-19 13:09 UTC, mafanya23 commented on docs/api/diagram_editor/toolbar/methods/getstate_method.md
> +// gets a state of all controls
the state of all controls

2024-03-19 13:15 UTC, mafanya23 commented on docs/api/diagram_editor/toolbar/methods/select_method.md
> +- `id` - (required) an ID of a Toolbar item to be selected. See the full list of items [here](api/diagram_editor/toolbar/config/items_property.md)
the ID of a Toolbar item

2024-03-19 13:17 UTC, mafanya23 commented on docs/api/diagram_editor/toolbar/methods/setfocus_method.md
> +@short: Checks if an input item of Toolbar is disabled
Мне кажется, тут должно быть другое описание, наверное перепуталось

2024-03-19 13:18 UTC, mafanya23 commented on docs/api/diagram_editor/toolbar/methods/setfocus_method.md
> +// checks if the "file" item is disabled
И комментарий, видимо, скопировался

2024-03-19 13:24 UTC, mafanya23 commented on docs/api/diagram_editor/toolbar/methods/unselect_method.md
> +- `id` - (optional) an ID of a Toolbar item to be unselected. See the full list of items [here](api/diagram_editor/toolbar/config/items_property.md)
the ID

2024-03-19 13:31 UTC, mafanya23 commented on docs/api/diagram_editor/toolbar/methods/treecollection_methods.md
> +| [add()](https://docs.dhtmlx.com/suite/tree_collection/api/treecollection_add_method.md)     | Adds an item to a component                                        |
Нужно пофиксить ссылки на методы tree collection

2024-03-19 13:35 UTC, mafanya23 commented on docs/api/diagram_editor/toolbar/config/navigationtype_property.md
> +- `"pointer"` - displayes the menu when a user hovers the mouse pointer over it
displays

2024-03-19 13:42 UTC, mafanya23 commented on docs/api/diagram_editor/toolbar/events/afterhide_event.md
> +// subscribe on the "afterHide" event
subscribe to

2024-03-19 13:45 UTC, mafanya23 commented on docs/api/diagram_editor/toolbar/events/treecollection_events.md
> +| [afterAdd](https://docs.dhtmlx.com/suite/tree_collection/api/treecollection_afteradd_event.md)       | Fires after adding a new item into a tree collection  |
Тут тоже нужно ссылки на ивенты подправить

2024-03-19 13:46 UTC, mafanya23 commented on docs/api/diagram_editor/toolbar/events/afterhide_event.md
> +// subscribe on the "afterHide" event
И в других событиях тоже этот коммент

2024-03-19 13:51 UTC, mafanya23 commented on docs/api/diagram_editor/toolbar/events/inputblur_event.md
> +@short: Fires on entering a text into the Toolbar input field
Описание такое же, как в input. Наверное, должно быть, как тут https://docs.dhtmlx.com/suite/toolbar/api/toolbar_inputblur_event/

2024-03-20 05:47 UTC, mafanya23 approved these changes

2024-03-20 07:34 UTC, merged