Update Shapebar properties
DHTMLX/docs-diagram pull request #15
Opened 2024-02-28 14:25 UTC by mafanya23

2024-03-14 13:52 UTC, Sorokin-Oleg requested changes

2024-03-14 13:52 UTC, Sorokin-Oleg commented on docs/api/diagram_editor/shapebar/config/css_property.md
> +const editor = new dhx.DiagramEditor("editor_container", {
@mafanya23 давай заменим пример на этот
```js
<script>
    const editor = new dhx.DiagramEditor("editor", {
        type: "default",
        view: {
            shapebar: {
                css: "custom_style",
            }
        }
    });
</script>

<style>
    .custom_style {
        background-color: var(--dhx-background-primary);
        font-size: var(--dhx-font-size-large);
    }
</style>
```

2024-03-14 13:52 UTC, Sorokin-Oleg commented on docs/api/diagram_editor/shapebar/config/width_property.md
> +            // other configurations
@mafanya23 можно опустить этот комментарий. Это было бы актуально, если мы скрываем обязательные свойства. А так, у нас все опциональны. Пример будет чище.

2024-03-14 13:52 UTC, Sorokin-Oleg commented on docs/api/diagram_editor/shapebar/config/width_property.md
> +const editor = new dhx.DiagramEditor("editor_container", {
@mafanya23 в разных примерах первым аргументом идут разные записи. Конечно, все будет работать. Но хотелось бы прийти к чему-то одному.
Я в примерах пишу `"editor"`, в документации и примерах можно встретить еще `"editor_container"`, `document.body`

2024-03-14 13:52 UTC, Sorokin-Oleg commented on docs/api/diagram_editor/shapebar/config/show_property.md
> +            // other configurations
@mafanya23 см. аналогичный комментарий

2024-03-14 13:52 UTC, Sorokin-Oleg commented on docs/api/diagram_editor/shapebar/config/show_property.md
> +const editor = new dhx.DiagramEditor("editor_container", {
@mafanya23 см. аналогичный комментарий

2024-03-14 13:52 UTC, Sorokin-Oleg commented on docs/api/diagram_editor/shapebar/config/preview_property.md
> +const editor = new dhx.DiagramEditor("editor_container", {
@mafanya23 см. аналогичный комментарий

2024-03-14 13:52 UTC, Sorokin-Oleg commented on docs/api/diagram_editor/shapebar/config/preview_property.md
> +            // other configurations
@mafanya23 см. аналогичный комментарий

2024-03-14 13:52 UTC, Sorokin-Oleg commented on docs/api/diagram_editor/shapebar/config/preview_property.md
> +        preview:{
@mafanya23 пробельчик добавить

2024-03-14 13:52 UTC, Sorokin-Oleg commented on docs/api/diagram_editor/shapebar/config/preview_property.md
> +const editor = new dhx.DiagramEditor("editor_container", {
@mafanya23 см. аналогичный комментарий

2024-03-14 13:52 UTC, Sorokin-Oleg commented on docs/api/diagram_editor/shapebar/config/preview_property.md
> +            // other configurations
@mafanya23 см. аналогичный комментарий

2024-03-14 13:52 UTC, Sorokin-Oleg commented on docs/api/diagram_editor/shapebar/config/preview_property.md
> +    defaults: defaults
@mafanya23 в современном стандарте, мы можем опустить присваивание если имя свойства и имя переменной совпадают.
В этой строчке будет так:
```
defaults,
```

2024-03-14 13:52 UTC, Sorokin-Oleg commented on docs/api/diagram_editor/shapebar/config/sections_property.md
> +const editor = new dhx.DiagramEditor("editor_container", {
@mafanya23 см. аналогичный комментарий

2024-03-18 16:37 UTC, Sorokin-Oleg approved these changes

2024-03-20 13:19 UTC, mafanya23 commented on docs/api/diagram_editor/shapebar/config/sections_property.md
> +The **sections** object can contain a set of *key:value* pairs where:
Поправила

2024-03-20 13:19 UTC, mafanya23 commented on docs/api/diagram_editor/shapebar/config/sections_property.md
> +- **value** - an array which can include:
Поправила

2024-03-20 13:34 UTC, Sorokin-Oleg commented on docs/api/diagram_editor/shapebar/config/css_property.md
> +<script>
@serhiipylypchuk1991 в конкретном примере этого делать нельзя. Пример перестанет работать. У Марии в примере все правильно, расширение `html`, в котором при помощи тегов разделяем код на js, css вставки.
Это же не svelte файл)) И даже там мы разделяем языковые вставки тегами

2024-03-20 14:14 UTC, Sorokin-Oleg commented on docs/api/diagram_editor/shapebar/config/css_property.md
> +<script>
> Ок, я просто для тулбара не давал описания стилей https://docs-next.dhtmlx.com/diagram/api/diagram_editor/toolbar/config/css_property/

Можно задать :) Тогда пример будет построен по аналогичному с этим принципом.

2024-03-20 14:15 UTC, merged