Add Line Titles docs
DHTMLX/docs-diagram pull request #18
Opened 2024-03-14 16:20 UTC by mafanya23

2024-03-15 09:30 UTC, Sorokin-Oleg requested changes

2024-03-15 09:30 UTC, Sorokin-Oleg commented on docs/guides/inline_editing.md
> +    // configuring shapes
@mafanya23 давай заменим на:
```
const data = [
    // configuring shapes
    { "id": "shape_1", "type": "start", "x": 0, "text": "Start" },
    { "id": "shape_2", "type": "process", "x": 400, "text": "Step 1" },
    // configuring a line
    {
        "id": "line_1",
        "type": "line",
        "from": "shape_1",
        "to": "shape_2",
    },
    // configuring a line title
    {   
        "id": "title_1", 
        "type": "lineTitle",
        "parent": "line_1", 
        "text": "Some text",
        "editable": false // disables inline editing of the text item of a line
    }
];
```

2024-03-15 09:30 UTC, Sorokin-Oleg commented on docs/guides/loading_data.md
>  const data = [
@mafanya23 давай заменим на этот датасет:
```
const data = [
	// configuring shapes
	{ "id": "shape_1", "type": "start", "x": 200, y: 0, "text": "Start" },
	{ "id": "shape_2", "type": "process", "x": 200, y: 120, "text": "Call Client and \n set-up Appointment" },
	{ "id": "shape_3", "type": "decision", "x": 200, "y": 240, "text": "Decision" },
	// configuring a line
	{ "id": "line_1", "type": "line", "from": "shape_1", "to": "shape_2" },
	{ "id": "line_2", "type": "dash", "from": "shape_2", "to": "shape_3" },
	// configuring a line title
	{ "id": "title_1", "type": "lineTitle", "parent": "line_1", "text": "Some text" },
];
```

2024-03-15 09:30 UTC, Sorokin-Oleg commented on docs/guides/loading_data.md
> +   {
@mafanya23 заменим на этот датасет. Вызов линий без фигур приведет к ошибке датаколекции
```
const data = [
	// configuring shapes
	{ "id": "shape_1", "type": "start", "x": 200, y: 0, "text": "Start" },
	{ "id": "shape_2", "type": "process", "x": 200, y: 120, "text": "Call Client and \n set-up Appointment" },
	{ "id": "shape_3", "type": "decision", "x": 200, "y": 240, "text": "Decision" },
	// configuring a line
	{ "id": "line_1", "type": "line", "from": "shape_1", "to": "shape_2" },
	{ "id": "line_2", "type": "dash", "from": "shape_2", "to": "shape_3" },
	// configuring a line title
	{ "id": "title_1", "type": "lineTitle", "parent": "line_1", "text": "Some text" },
];
```

2024-03-15 09:30 UTC, Sorokin-Oleg commented on docs/guides/loading_data.md
> +    { "type": "line", "id": "line_1", "from": "shape_1", "to": "shape_2" },
@mafanya23 тоже, что и выше. Линии без фигур не могут существовать.
```
const data = [
	// configuring shapes
	{ "id": "shape_1", "type": "start", "x": 200, y: 0, "text": "Start" },
	{ "id": "shape_2", "type": "process", "x": 200, y: 120, "text": "Call Client and \n set-up Appointment" },
	{ "id": "shape_3", "type": "decision", "x": 200, "y": 240, "text": "Decision" },
	// configuring a line
	{ "id": "line_1", "type": "line", "from": "shape_1", "to": "shape_2" },
	{ "id": "line_2", "type": "dash", "from": "shape_2", "to": "shape_3" },
	// configuring a line title
	{ "id": "title_1", "type": "lineTitle", "parent": "line_1", "text": "Some text" },
];
```
Можно подсветить конкретные строчки в описаниях

2024-03-15 09:30 UTC, Sorokin-Oleg commented on docs/guides/inline_editing.md
> +                { "text": "October", "fill": "rgba(155, 96, 248, 0.4)", "editable": true },
@mafanya23 заметка. Когда займусь примерами, обрати пожалуйста внимание, если я забуду. На значения цветов. Оно изменится. Так как Colorpicker поддерживает только `HEX`. Да, сами фигуры работают со всеми форматами, но в Editbar они не отобразятся.

2024-03-19 07:10 UTC, mafanya23 commented on docs/lines/configuration_properties.md
>  ---
Поправила для всех items

2024-03-19 07:18 UTC, mafanya23 commented on docs/lines/configuration_properties.md
> +sidebar_label: Line properties !!
Поправила для line и shape, в остальных верно указано

2024-03-19 07:31 UTC, mafanya23 commented on docs/guides/inline_editing.md
> +    // configuring shapes
Заменила

2024-03-19 07:48 UTC, mafanya23 commented on docs/guides/inline_editing.md
> +                { "text": "October", "fill": "rgba(155, 96, 248, 0.4)", "editable": true },
Хорошо, пометила себе

2024-03-19 09:25 UTC, Sorokin-Oleg approved these changes

2024-03-20 07:00 UTC, mafanya23 commented on docs/groups/configuration_properties.md
> +{{note While specifying color values of the item, use the HEX format.}}
Да, спасибо, пропустила этот момент

2024-03-20 07:05 UTC, mafanya23 commented on docs/line_titles/index.md
> +{{note LineTitles are available only in the default mode of Diagram/Diagram Editor (type: "default").}}
Поправила

2024-03-20 07:11 UTC, mafanya23 commented on docs/line_titles/index.md
> +{{note The examples below are suitable both for Diagram and Diagram Editor.}}
Поправила

2024-03-20 07:11 UTC, mafanya23 commented on docs/line_titles/index.md
> +}}
Поправила

2024-03-20 07:11 UTC, Sorokin-Oleg commented on docs/guides/inline_editing.md
> +                { "text": "October", "fill": "rgba(155, 96, 248, 0.4)", "editable": true },
> а нужно ли название свойства оборачивать в ковычки внутри объекта? Это же моветон вроде...

@mafanya23 @serhiipylypchuk1991 Определенно нужно. В качестве данных diagram использует формат JSON, который в обычном виде хранится на сервере. Если у ключа не будет кавычек, для JSON это ошибка. Если совсем придраться, то нужно следить, чтобы у последнего элемента данных в конце отсутствовала запятая, при ее наличии также будет ошибка. 
Запись без соблюдения спецификации работает в JS, поэтому мы и не ловим ошибок в примерах. Но если бы данные подгружались с сервера, и ответ никак не обрабатывался, то ошибка неизбежна.

Немного про формат https://en.wikipedia.org/wiki/JSON

2024-03-20 07:11 UTC, mafanya23 commented on docs/lines/configuration_properties.md
Поправила

2024-03-20 07:12 UTC, mafanya23 commented on docs/shapes/configuration_properties.md
> +{{note While specifying color values of the item, use the HEX format.}}
Поправила

2024-03-20 08:01 UTC, Sorokin-Oleg commented on docs/guides/inline_editing.md
> +                { "text": "October", "fill": "rgba(155, 96, 248, 0.4)", "editable": true },
> Но речь же идет только про свойства внутри объекта данных?

Да. В конфигурации компонента кавычки не нужны, это JS кухня. В данном случае, пример, это данные.

2024-03-20 12:46 UTC, merged