Update Diagram to the latest Suite version
DHTMLX/docs-diagram pull request #2
Opened 2023-11-17 09:23 UTC by mafanya23

2023-12-13 14:55 UTC, Sorokin-Oleg requested changes

2023-12-13 14:55 UTC, Sorokin-Oleg commented on docs/guides/themes/setting_theme.md
> +    const diagram = new dhx.Diagram("container", {
@mafanya23 в примере фигурирует `container-1`, тут `container`. Скорее всего где-то ошибка. Думаю, что в названии `container-1`

2023-12-13 14:55 UTC, Sorokin-Oleg commented on docs/guides/themes/setting_theme.md
> +- setting a theme for the Toolbar control of DiagramEditor
@mafanya23 все как бы не плохо. Но пример в задаче был показан с целью того, что можно перекрасить в необходимую тему практически любой компонент редактора. Выбор пал на Toolbar, так как в тот момент с API было все понятно. Однако у нас есть возможность провернуть данное действие и с Shapebar/Editbar/Toolbar

Этот момент хотелось бы как-то выделить.

2023-12-13 14:55 UTC, Sorokin-Oleg commented on docs/guides/themes/base_themes_configuration.md
> +<script>
```
<script>
    const diagram = new dhx.Diagram("diagram_container");
    ...
    dhx.setTheme("light");
</script>
```

@mafanya23 есть еще один момент. Это единственный пример, кроме примеров на странице установки тем. Где есть пример с установкой. Хотелось бы определится, либо показываем везде, либо только в одном месте. Как по мне странновато конечно читать про темы, не зная как их установить. Но под это есть отдельный раздел...

2023-12-13 14:55 UTC, Sorokin-Oleg commented on docs/guides/themes/setting_theme.md
> +### Changing the "data" attribute
@mafanya23 все же думаю, что не изменением, а `установкой`.
- При помощи установления `data` атрибута

2023-12-13 14:55 UTC, Sorokin-Oleg commented on docs/guides/themes/setting_theme.md
> +//your code here
@mafanya23 коммент будет лишним. Знаю, что это с документации suite. Но там далеко от идеала.

2023-12-13 14:55 UTC, Sorokin-Oleg commented on docs/guides/themes/setting_theme.md
> +- change the **"data-dhx-theme"** attribute for the *root* element:
@mafanya23 `change` не очень корректное описание поведения. Как и выше, мы устанавливаем дата атрибут с определенным значением

2023-12-13 14:55 UTC, Sorokin-Oleg commented on docs/guides/themes/setting_theme.md
> +- change the **"data-dhx-theme"** attribute for the *root* element:
@mafanya23 тут может быть в принципе любой HTML Element, на который возможно установить дата атрибут. Просто в примере мы устанавливаем тему на `documentElement`

2023-12-14 08:27 UTC, mafanya23 commented on docs/guides/themes/setting_theme.md
> +- setting a theme for the Toolbar control of DiagramEditor
Добавила про возможность установки темы для контролов редактора

2023-12-14 08:58 UTC, mafanya23 commented on docs/guides/themes/base_themes_configuration.md
> +<script>
Согласна. Все-таки перенесла статью с установкой в общую с темами. В примеры статей про конфигурацию и кастомную тему добавила установку

2023-12-15 08:41 UTC, Sorokin-Oleg requested changes

2023-12-15 08:41 UTC, Sorokin-Oleg commented on docs/guides/themes/themes.md
> +<script>
@mafanya23 давай этот пример уберем, и оставим пример, тот, что ниже с toolbar. Они по своей сути одинаковы. Описание для нижнего случая можно дополнить тем, что можно это провернуть с любым элементом.

2023-12-18 08:00 UTC, Sorokin-Oleg approved these changes

2023-12-18 09:33 UTC, Sorokin-Oleg commented on docs/api/data_collection/getfilters_method.md
> +getFilters({ permanent?: boolean }): { [key: string]: { rule: object | callback, config: object } };
@mafanya23 @serhiipylypchuk1991 да, тут можно таким образом
```
getFilters({ permanent?: boolean }): object;
```
С описание возвращаемого объекта

2023-12-18 12:17 UTC, mafanya23 commented on docs/api/data_collection/filter_method.md
>  ### Parameters
Убрала типы из параметров, перенесла их в Usage

2023-12-19 07:21 UTC, merged