Draft: Update Editor localization
DHTMLX/docs-diagram pull request #20
Opened 2024-03-20 14:06 UTC by serhiipylypchuk1991

2024-03-20 15:15 UTC, Sorokin-Oleg approved these changes

2024-03-21 12:04 UTC, mafanya23 requested changes

2024-03-21 12:04 UTC, mafanya23 commented on docs/guides/localization.md
> +        alignHorizontalCenter: "Horizontal centers",
center

2024-03-21 12:04 UTC, mafanya23 commented on docs/guides/localization.md
> +        alignVerticalCenter: "Vertical centers",
center

2024-03-21 12:05 UTC, mafanya23 commented
@Sorokin-Oleg надо будет в коде тоже подправить локаль

2024-03-21 12:27 UTC, Sorokin-Oleg commented on docs/guides/localization.md
> +        connectionPoints: "Connection Points",
Замена на - `connectionPoints: "Connection points",`

2024-03-21 12:27 UTC, Sorokin-Oleg commented on docs/guides/localization.md
> +        resizePoints: "Resize Points",
Замена на - `resizePoints: "Resize points",`

2024-03-21 12:28 UTC, Sorokin-Oleg commented
> centers

Исправлено

2024-03-21 17:15 UTC, mafanya23 approved these changes

2024-03-22 06:17 UTC, merged