Draft: Add full description of the items property
DHTMLX/docs-diagram pull request #23
Opened 2024-03-25 12:21 UTC by serhiipylypchuk1991

2024-03-26 13:10 UTC, Sorokin-Oleg commented
@serhiipylypchuk1991 необходимо произвести замену изображений с стандартной цветовой схемой. В данный момент, все изображения в фиолетовых оттенках.

2024-03-26 14:19 UTC, Sorokin-Oleg requested changes

2024-03-26 14:19 UTC, Sorokin-Oleg commented on docs/api/diagram_editor/toolbar/config/items_property.md
> +- `value` - (optional) - the labe of a service element
@serhiipylypchuk1991 может как-то перефразировать? Все же это отображаемое значение.

2024-03-26 14:19 UTC, Sorokin-Oleg commented on docs/api/diagram_editor/toolbar/config/items_property.md
> +- `value` - (optional) - the labe of a service element
`labe` -> `label`?

2024-03-26 14:19 UTC, Sorokin-Oleg commented on docs/api/diagram_editor/toolbar/config/items_property.md
> +- `icon` - (optional) - the icon of a service element
@serhiipylypchuk1991 
> Устанавливает класс иконки сервисного элемента

2024-03-26 14:19 UTC, Sorokin-Oleg commented on docs/api/diagram_editor/toolbar/config/items_property.md
> +- `checkIcon` - (optional) - the handler that allows you to define the icon class. It takes the Diagram Editor object as an argument and returns the icon css class
@serhiipylypchuk1991  `takes` :) Да не может он ничего принимать) Он вызывается с объектом в качестве аргумента.

2024-03-26 14:19 UTC, Sorokin-Oleg commented on docs/api/diagram_editor/toolbar/config/items_property.md
> +- `handler` - (optional) - the handler that runs when the ***click*** or ***inputChange*** events occurs. It takes the Diagram Editor object and a [native event](https://developer.mozilla.org/en-US/d
@serhiipylypchuk1991 `takes`

2024-03-26 14:19 UTC, Sorokin-Oleg commented on docs/api/diagram_editor/toolbar/config/items_property.md
> +    - `selectNone` - deselects all the available items
@serhiipylypchuk1991 не критично, обычно применяем `unselect`

2024-03-26 14:22 UTC, Sorokin-Oleg commented
По Toolbar items, и в целом по работе с toolbar хотелось гайд сделать

2024-03-29 13:41 UTC, Sorokin-Oleg requested changes

2024-03-29 13:41 UTC, Sorokin-Oleg commented on docs/api/diagram_editor/toolbar/config/items_property.md
>      }, {...}
@serhiipylypchuk1991 убежало куда-то свойство `items` :). Я его в документации не описывал, но в примерах оно фигурирует. Обсуждали с тобой на созвоне. 
Давай покажем следующим образом:
```
items: [ 
    {
        type: string;
        id?: string;
        value?: string;
        hotkey?: string;
        icon?: string;
        hidden?: boolean;
        disabled?: boolean;
        css?: string | string[];
        items?: (string | object)[];
        checkIcon?: (editor: object) => string;
        handler?: (editor: object, event: Event) => void;
    }, {...} 
]
```
- `items` - optional - определяет структуру дочерних элементов;

2024-03-29 13:41 UTC, Sorokin-Oleg commented on docs/api/diagram_editor/toolbar/config/items_property.md
> +const editor = new dhx.DiagramEditor("editor", {
@serhiipylypchuk1991 С Машей решили, что название id в качестве контейнера будет как "editor_config". Давай в тех местах, где встречается "editor" заменим на принятый.
В моих примерах в основном был "editor".

2024-03-29 13:41 UTC, Sorokin-Oleg commented on docs/api/diagram_editor/toolbar/config/items_property.md
> +                                        console.log("some logic")
@serhiipylypchuk1991 давай уберем `console.log` и вместо напишем в комментарии
```
// Тут может быть ваш сценарий 
```
(что-то в этом духе)

2024-03-29 13:41 UTC, Sorokin-Oleg commented on docs/guides/diagram_editor/toolbar.md
> +                                        console.log("some logic")
@serhiipylypchuk1991 выше дал комментарий по поводу этой строчки

2024-03-29 13:41 UTC, Sorokin-Oleg commented on docs/guides/diagram_editor/toolbar.md
> +- [`items`](api/diagram_editor/toolbar/config/items_property.md) - the array of [**service elements**](#service-elements) (controls) arranged on Toolbar. There are 2 ways how to configure items:
@serhiipylypchuk1991 но ведь не обязательно массив будет состоять из сервисных элементов. Можно сделать так, что все элементы будут исключительно пользовательскими. Думаю, что тут не нужно подчеркивать, просто элементы.

2024-03-29 13:41 UTC, Sorokin-Oleg commented on docs/guides/diagram_editor/toolbar.md
> +handler?: (editor: obj, event: Event) => void;
@serhiipylypchuk1991 obj -> object

2024-03-29 13:41 UTC, Sorokin-Oleg commented on docs/guides/diagram_editor/toolbar.md
> +                }
@serhiipylypchuk1991 отступы `type: "button", value: "Best button",`

2024-03-29 13:52 UTC, mafanya23 commented on docs/api/diagram_editor/toolbar/config/items_property.md
> +const editor = new dhx.DiagramEditor("editor", {
"editor_container" :)

2024-04-01 11:49 UTC, Sorokin-Oleg requested changes

2024-04-01 11:49 UTC, Sorokin-Oleg commented on docs/api/diagram_editor/toolbar/config/items_property.md
> +        id?: string,
@serhiipylypchuk1991 замени пожалуйста этой кодовой вставкой. Он с предыдущего запроса. Тут учтен необходимый порядок, и синтаксис.
```
items: [ 
    {
        type: string;
        id?: string;
        value?: string;
        hotkey?: string;
        icon?: string;
        hidden?: boolean;
        disabled?: boolean;
        css?: string | string[];
        items?: (string | object)[];
        checkIcon?: (editor: object) => string;
        handler?: (editor: object, event: Event) => void;
    }, {...} 
]
```

2024-04-01 13:31 UTC, mafanya23 requested changes

2024-04-01 13:31 UTC, mafanya23 commented on docs/guides/diagram_editor/toolbar.md
> +- **scale** - the control that allows user to increase or decrease the scale value by 0.05 (5%)
allows a/the user

2024-04-01 13:31 UTC, mafanya23 commented on docs/guides/diagram_editor/toolbar.md
> +Besides [**Service elements**](#service-elements), you can also specify and configure the following **Base elements** using the [object](api/diagram_editor/toolbar/config/items_property.md/#configuri
в ссылку на items старый якорь

2024-04-01 13:31 UTC, mafanya23 commented on docs/guides/diagram_editor/toolbar.md
> +The example below shows how to add the [Button](https://docs.dhtmlx.com/suite/toolbar/button/) conrol to the Toolbar:
control

2024-04-01 13:31 UTC, mafanya23 commented on docs/guides/diagram_editor/toolbar.md
> +~~~jsx{6-9}
не хватает пробела, сбилась подсветка кода

2024-04-01 13:31 UTC, mafanya23 commented on docs/guides/diagram_editor/toolbar.md
> +- `handler` - (optional) - the handler that runs when the ***click*** or ***inputChange*** events occurs. It is called with the following arguments:
event occurs / events occur

2024-04-02 08:17 UTC, merged