Customization of shapebar items
DHTMLX/docs-diagram pull request #24
Opened 2024-03-29 10:47 UTC by mafanya23

2024-03-29 12:15 UTC, Sorokin-Oleg requested changes
В целом все хорошо. Но хотелось бы ссылок на возможность изменения цветовой схемы элементов где-то поближе к пользователю. Например в гайдах shapebar. 
Нужно было наследоваться от ветки с shapebar гайдами (https://github.com/DHTMLX/docs-diagram/pull/22)

2024-03-29 12:15 UTC, Sorokin-Oleg commented on docs/guides/themes/themes.md
> +	...
@mafanya23 вместо `...` давай добавим эти переменные, я что-то не посмотрел, что мы их не описали.
```
    /* DHTMLX Diagram variables*/
    --dhx-selected-border: 1px solid var(--dhx-color-primary);
    --dhx-selected-border-dashed: 1px dashed var(--dhx-color-primary);

    --dhx-shapebar-item-font-color: #4C4C4C;
    --dhx-shapebar-item-background: #EEF1F6;
    --dhx-shapebar-item-border-color: #B8C6D6;
    /* end DHTMLX Diagram variables*/
```

2024-03-29 12:15 UTC, Sorokin-Oleg commented on docs/guides/themes/themes.md
> +	...
@mafanya23 там ниже в примерах есть места с разным наименованием `editor`, `container`. Давай сейчас если будем встречать примеры, то приведем их к виду `editor_container` при необходимости

2024-03-29 12:15 UTC, Sorokin-Oleg commented on docs/guides/themes/base_themes_configuration.md
> +You can manage the color scheme of Shapebar items by using your own CSS variables. For this, you should define a custom CSS variable and specify it as a value of the necessary property in the `defaul
@mafanya23 в первую очередь для этого есть 3 переменные, которыми он может полностью кастомизировать панель. А уже потом то, что тут описано.

2024-03-29 13:16 UTC, mafanya23 commented on docs/guides/themes/themes.md
> +	...
Хорошо, тут поправила

2024-04-01 10:29 UTC, Sorokin-Oleg commented
@mafanya23 а можешь отсюда пользователя направить на гайды? http://localhost:3000/diagram/api/diagram_editor/shapebar/config/css_property/

2024-04-01 10:33 UTC, Sorokin-Oleg approved these changes

2024-04-02 08:25 UTC, merged