API overview pages for toolbar/shapebar/editbar
DHTMLX/docs-diagram pull request #27
Opened 2024-04-04 11:48 UTC by mafanya23

2024-04-25 08:24 UTC, Sorokin-Oleg requested changes

2024-04-25 08:24 UTC, Sorokin-Oleg commented on docs/api/diagram_editor/copymanager/api_overview.md
> +
@mafanya23 давай тут `...` добавим

2024-04-25 08:24 UTC, Sorokin-Oleg commented on docs/api/diagram_editor/historymanager/api_overview.md
> +
@mafanya23 давай тут `...` добавим

2024-04-25 08:24 UTC, Sorokin-Oleg commented on docs/api/diagram_editor/historymanager/api_overview.md
> +editor.history.redo(); // copies selected items
@mafanya23 что-что делает? :)) Комментарий

2024-04-25 08:24 UTC, Sorokin-Oleg commented on docs/api/diagram_editor/historymanager/api_overview.md
> +| [](api/diagram_editor/historymanager/config/disabled_property.md) | @getshort(api/diagram_editor/historymanager/config/disabled_property.md) |
@mafanya23 стоит убрать, у нас есть методы disable/enable

2024-04-25 08:24 UTC, Sorokin-Oleg commented on docs/api/diagram_editor/historymanager/config/overview.md
> +| [](api/diagram_editor/historymanager/config/disabled_property.md) | @getshort(api/diagram_editor/historymanager/config/disabled_property.md) |
@mafanya23 убираем свойство `disabled` из документации

2024-04-25 08:24 UTC, Sorokin-Oleg commented on docs/api/diagram_editor/historymanager/config/savedelay_property.md
> +editor.history.saveDelay = 600;
@mafanya23 давай задержку в 1000 сделаем

2024-04-25 08:24 UTC, Sorokin-Oleg commented on docs/api/diagram_editor/historymanager/methods/isredo_method.md
> -isUndo(): boolean;
@mafanya23 куда `isUndo` убежало?)

2024-04-25 09:33 UTC, mafanya23 commented on docs/api/diagram_editor/historymanager/api_overview.md
> +editor.history.redo(); // copies selected items
Упс, спасибо)

2024-04-29 07:24 UTC, Sorokin-Oleg approved these changes

2024-04-29 07:49 UTC, merged