[update] Editbar guides structure
DHTMLX/docs-diagram pull request #29
Opened 2024-04-10 10:27 UTC by serhiipylypchuk1991

2024-04-10 13:19 UTC, mafanya23 requested changes

2024-04-10 13:19 UTC, mafanya23 commented on docs/api/diagram_editor/editbar/config/properties_property.md
> +
Сбились параметры для function в списке

2024-04-10 13:19 UTC, mafanya23 commented on docs/api/diagram_editor/editbar/config/properties_property.md
> +        ({ item, editor }) => { // the callback function that return the configuration object
returns

2024-04-10 13:24 UTC, mafanya23 approved these changes

2024-04-11 06:34 UTC, Sorokin-Oleg commented on docs/api/diagram_editor/editbar/config/properties_property.md
> +    ... // another control
@serhiipylypchuk1991 на всякий)) Это не контролы. Ниже тоже не контролы.

2024-04-11 07:10 UTC, merged