Editbar basic controls
DHTMLX/docs-diagram pull request #30
Opened 2024-04-19 08:38 UTC by mafanya23

2024-04-22 10:00 UTC, Sorokin-Oleg requested changes

2024-04-22 10:00 UTC, Sorokin-Oleg commented on docs/guides/diagram_editor/editbar/basic_controls/avatar.md
> +@short: A control for uploading of an avatar.
@mafanya23 для загрузки изображений, было бы лучше.

2024-04-22 10:00 UTC, Sorokin-Oleg commented on docs/guides/diagram_editor/editbar/basic_controls/avatar.md
> +    key?: string,
@mafanya23 `// "img" by default`

2024-04-22 10:00 UTC, Sorokin-Oleg commented on docs/guides/diagram_editor/editbar/basic_controls/avatar.md
> +- `key` - (optional) the name of the specified/modified property or the path to it in the object of a Diagram item (shape, line, group, swimlane)
@mafanya23 в этом описании без `path`. То, что в скобочках было для вас, как контекст для понимания, в документации это можно не отображать.
```
the name of the specified/modified property in the object of a Diagram item
```

2024-04-22 10:00 UTC, Sorokin-Oleg commented on docs/guides/diagram_editor/editbar/basic_controls/avatar.md
> +- `preview` - (optional) specifies the absolute path to the preview image. The preview image is visible, when the `value` is not defined
@mafanya23 `The preview image is visible, when the `value` is not defined` - тут просто, когда изображение не загружено. Так как свойства `value` у нас нет.

2024-04-22 10:00 UTC, Sorokin-Oleg commented on docs/guides/diagram_editor/editbar/basic_controls/avatar.md
> +- `size` - (optional) allows setting one of the three basic control's sizes: *"small" | "medium" | "large"* , or applying a custom size, *"medium"* by default
@mafanya23 пользовательский размер в `px`

2024-04-22 10:00 UTC, Sorokin-Oleg commented on docs/guides/diagram_editor/editbar/basic_controls/avatar.md
> +- `padding` - (optional) sets padding between a cell and a border of the Avatar control, *"8px"* by default
@mafanya23 нет, по умолчанию тут не 8px. В suite кто-то эту запись скопировал для всех элементов. И это не так. Все актуальные значения по-умолчанию можно найти в комментариях в usage, задачи.

2024-04-22 10:00 UTC, Sorokin-Oleg commented on docs/guides/diagram_editor/editbar/basic_controls/avatar.md
> +            - `id` - the id of a Diagram item (shape, line, group, swimlane)
@mafanya23 скобочки для вас

2024-04-22 10:00 UTC, Sorokin-Oleg commented on docs/guides/diagram_editor/editbar/basic_controls/avatar.md
> +        - `arguments` - (optional) - the original event arguments
@mafanya23 было бы не плохо оставлять ссылку на оригинальные события.

2024-04-22 10:00 UTC, Sorokin-Oleg commented on docs/guides/diagram_editor/editbar/basic_controls/avatar.md
> +        - `id` - the id of a Diagram item (shape, line, group, swimlane)
@mafanya23 эти скобочки не для доки

2024-04-22 10:00 UTC, Sorokin-Oleg commented on docs/guides/diagram_editor/editbar/basic_controls/avatar.md
> +        - `value` - the value of a Diagram item (shape, line, group, swimlane)
@mafanya23 скобочки не для доки

2024-04-22 10:00 UTC, Sorokin-Oleg commented on docs/guides/diagram_editor/editbar/basic_controls/avatar.md
> +            - `control` - the form control
@mafanya23 можно ссылку, на сам контрол (дока suite). Либо, чтобы все не дублировать, где-то ниже ссылку привести

2024-04-24 08:22 UTC, Sorokin-Oleg approved these changes

2024-04-24 08:22 UTC, Sorokin-Oleg commented on docs/guides/diagram_editor/editbar/basic_controls/checkbox.md
> +@short: A control that allows a user to make a choice between one or several opposite options by toggling them.
@mafanya23 эм)) Мы можем управлять только одним состоянием. Тут не может быть речи о нескольких*, или между*

2024-04-25 07:03 UTC, Sorokin-Oleg commented on docs/guides/diagram_editor/editbar/basic_controls/avatar.md
> +                            "firstCustomParam": "customValue",
В конфигурации компонента запятые не критичны, так как это JS, а не JSON формат

2024-04-25 07:04 UTC, Sorokin-Oleg commented on docs/guides/diagram_editor/editbar/basic_controls/avatar.md
> +                            "firstCustomParam": "customValue",
Если бы это были бы данные, то да, так как данные приходят у нас как JSON, в основном

2024-04-25 07:04 UTC, mafanya23 commented on docs/guides/diagram_editor/editbar/basic_controls/avatar.md
> +description: You can explore the Avatar of Editbar in the documentation of the the DHTMLX JavaScript Diagram library. Browse developer guides and API reference, try out code examples and live demos,
Пропустила, спасибо

2024-04-25 07:07 UTC, mafanya23 commented on docs/guides/diagram_editor/editbar/basic_controls/avatar.md
> +description: You can explore the Avatar of Editbar in the documentation of the the DHTMLX JavaScript Diagram library. Browse developer guides and API reference, try out code examples and live demos,
Добавила

2024-04-25 07:25 UTC, Sorokin-Oleg requested changes

2024-04-25 07:25 UTC, Sorokin-Oleg commented on docs/guides/diagram_editor/editbar/basic_controls/button.md
> +:::
@mafanya23 @serhiipylypchuk1991 конкретно это предупреждение здесь уместно. Предупреждение, что выше. Будет уместно в описании непосредственно свойств `properties`, `controls`. Здесь оно избыточно.

2024-04-25 07:25 UTC, Sorokin-Oleg commented on docs/guides/diagram_editor/editbar/basic_controls/button.md
> +:::warning
@mafanya23 предупреждение для свойств `properties`, `controls`, можно также в гайд поместить. В базовых контролах не нужно.

2024-04-26 07:02 UTC, mafanya23 commented on docs/guides/diagram_editor/editbar/basic_controls/fieldset.md
> +- `labelAlignment` - (optional) defines the position of the label: *"left" | "right" | "center"*. *"left"* by default
Согласна, поправлю)

2024-04-26 07:46 UTC, merged