Draft. Complex contols for Diagram editor
DHTMLX/docs-diagram pull request #31
Opened 2024-04-23 20:36 UTC by serhiipylypchuk1991

2024-04-24 10:59 UTC, Sorokin-Oleg requested changes

2024-04-24 10:59 UTC, Sorokin-Oleg commented on docs/guides/diagram_editor/editbar/complex_controls/arrange.md
> +![Arrange control](../../../../assets/arrange_type.png)
@serhiipylypchuk1991 изображения необходимо актуализировать.

2024-04-24 10:59 UTC, Sorokin-Oleg commented on docs/guides/diagram_editor/editbar/complex_controls/arrange.md
> +    compact?: boolean, // ??? by default
@serhiipylypchuk1991 false

2024-04-24 10:59 UTC, Sorokin-Oleg commented on docs/guides/diagram_editor/editbar/complex_controls/arrange.md
> +const editor= new dhx.DiagramEditor("editor", {
@serhiipylypchuk1991 "editor_container" вроде так с Машей договорились, примеры в задаче были написаны до обсуждения.

2024-04-24 10:59 UTC, Sorokin-Oleg commented on docs/guides/diagram_editor/editbar/complex_controls/arrange.md
> +:::warning
@serhiipylypchuk1991 @mafanya23 важная заметка. Не допускается переопределение типа контрола в свойстве `controls`. В `properties` это не так опасно, и допускается, что будет встречаться в примерах. Стоит вынести акцент на controls. Это актуально и для basic controls.

Поясню. Если мы захотели создать новый контрол, и указали существующее название, то это тот момент про который идет речь. Сбой в функциональности можно вызвать только в basic controls переопределив там сервисные методы. Для complex это не так актуально.

2024-04-24 10:59 UTC, Sorokin-Oleg commented on docs/guides/diagram_editor/editbar/complex_controls/border.md
> +- `padding` - (optional) sets the padding for the content inside the control group. *"8px"* by default
@serhiipylypchuk1991 в usage другая цифра к default value

2024-04-24 10:59 UTC, Sorokin-Oleg commented on docs/guides/diagram_editor/editbar/complex_controls/border.md
> +:::warning
Основной комментарий выше

2024-04-24 10:59 UTC, Sorokin-Oleg commented on docs/guides/diagram_editor/editbar/complex_controls/border.md
> +    compact?: boolean, // ??? by default
@serhiipylypchuk1991 false

2024-04-24 10:59 UTC, Sorokin-Oleg commented on docs/guides/diagram_editor/editbar/complex_controls/arrange.md
> +    compact?: boolean, // ??? by default
@serhiipylypchuk1991 давай свойство повыше установим, все же оно к сервисным не относится (мой промах)

2024-04-24 10:59 UTC, Sorokin-Oleg commented on docs/guides/diagram_editor/editbar/complex_controls/arrange.md
> +- `compact` - (optional) specifies the compact mode, removes indents and frame
@serhiipylypchuk1991 уберем из сервисных, повыше

2024-04-24 10:59 UTC, Sorokin-Oleg commented on docs/guides/diagram_editor/editbar/complex_controls/border.md
> +- `compact` - (optional) specifies the compact mode, removes indents and frame
@serhiipylypchuk1991 уберем из сервисных повыше

2024-04-24 10:59 UTC, Sorokin-Oleg commented on docs/guides/diagram_editor/editbar/complex_controls/gridstep.md
> +    wrap?: boolean // true by default
@serhiipylypchuk1991 уберем из сервисных, повыше

2024-04-24 10:59 UTC, Sorokin-Oleg commented on docs/guides/diagram_editor/editbar/complex_controls/gridstep.md
> +- `wrap` - (optional) allows displaying the external wrapping. *true* by default
@serhiipylypchuk1991 уберем из сервисных

2024-04-24 10:59 UTC, Sorokin-Oleg commented on docs/guides/diagram_editor/editbar/complex_controls/gridstep.md
> +                $shape: [
@serhiipylypchuk1991 давай $shape на $default в этом примере заменим. И "editor_container"

2024-04-24 10:59 UTC, Sorokin-Oleg commented on docs/guides/diagram_editor/editbar/complex_controls/header.md
> +@short: The complex control for displaying and modifying the "group" and "swimlane" elements of the Diagram editor
@serhiipylypchuk1991 для управления свойствами заголовка "group", "swimlane"

2024-04-24 10:59 UTC, Sorokin-Oleg commented on docs/guides/diagram_editor/editbar/complex_controls/gridstep.md
> +- `padding` - (optional) sets the padding for the content inside the control group. *"8px"* by default
@serhiipylypchuk1991 смотри usage

2024-04-24 10:59 UTC, Sorokin-Oleg commented on docs/guides/diagram_editor/editbar/complex_controls/header.md
> +- `padding` - (optional) sets the padding for the content inside the control group. *"8px"* by default
@serhiipylypchuk1991 см usage

2024-04-24 10:59 UTC, Sorokin-Oleg commented on docs/guides/diagram_editor/editbar/complex_controls/header.md
> +- `compact` - (optional) specifies the compact mode, removes indents and frames
@serhiipylypchuk1991 убираем из сервисных, переносим выше

2024-04-24 10:59 UTC, Sorokin-Oleg commented on docs/guides/diagram_editor/editbar/complex_controls/header.md
> +const editor= new dhx.DiagramEditor("editor", {
@serhiipylypchuk1991 editor_container

2024-04-24 10:59 UTC, Sorokin-Oleg commented on docs/guides/diagram_editor/editbar/complex_controls/headercommon.md
> +    compact?: boolean, // ??? by default
@serhiipylypchuk1991 убираем из сервисных переносим выше

2024-04-24 10:59 UTC, Sorokin-Oleg commented on docs/guides/diagram_editor/editbar/complex_controls/headercommon.md
> +- `padding` - (optional) sets the padding for the content inside the control group. *"8px"* by default
@serhiipylypchuk1991 не верное значение по-умолчанию

2024-04-24 10:59 UTC, Sorokin-Oleg commented on docs/guides/diagram_editor/editbar/complex_controls/headercommon.md
> +- `compact` - (optional) specifies the compact mode, removes indents and frame
@serhiipylypchuk1991 переносим в common

2024-04-24 10:59 UTC, Sorokin-Oleg commented on docs/guides/diagram_editor/editbar/complex_controls/headercommon.md
> +:::warning
@serhiipylypchuk1991 примечание выше

2024-04-24 10:59 UTC, Sorokin-Oleg commented on docs/guides/diagram_editor/editbar/complex_controls/headercommon.md
> +const editor= new dhx.DiagramEditor("editor", {
@serhiipylypchuk1991 editor_container

2024-04-24 10:59 UTC, Sorokin-Oleg commented on docs/guides/diagram_editor/editbar/complex_controls/headerposition.md
> +    compact?: boolean, // ??? by default
@serhiipylypchuk1991 переносим выше, false by default

2024-04-24 10:59 UTC, Sorokin-Oleg commented on docs/guides/diagram_editor/editbar/complex_controls/headerposition.md
> +- `padding` - (optional) sets the padding for the content inside the control group. *"8px"* by default
@serhiipylypchuk1991 не 8px

2024-04-24 10:59 UTC, Sorokin-Oleg commented on docs/guides/diagram_editor/editbar/complex_controls/headerposition.md
> +:::warning
@serhiipylypchuk1991 заметка выше

2024-04-24 10:59 UTC, Sorokin-Oleg commented on docs/guides/diagram_editor/editbar/complex_controls/headerposition.md
> +- `compact` - (optional) specifies the compact mode, removes indents and frame
@serhiipylypchuk1991 переносим выше

2024-04-24 10:59 UTC, Sorokin-Oleg commented on docs/guides/diagram_editor/editbar/complex_controls/headerposition.md
> +const editor= new dhx.DiagramEditor("editor", {
@serhiipylypchuk1991 editor_container

2024-04-24 10:59 UTC, Sorokin-Oleg commented on docs/guides/diagram_editor/editbar/complex_controls/lineshape.md
> +    compact?: boolean, // ??? by default
@serhiipylypchuk1991 перенесем повыше, из сервисных. False by default

2024-04-24 10:59 UTC, Sorokin-Oleg commented on docs/guides/diagram_editor/editbar/complex_controls/lineshape.md
> +- `padding` - (optional) sets the padding for the content inside the control group. *"8px"* by default
@serhiipylypchuk1991 "0 16px"

2024-04-24 10:59 UTC, Sorokin-Oleg commented on docs/guides/diagram_editor/editbar/complex_controls/lineshape.md
> +:::warning
@serhiipylypchuk1991 заметка выше

2024-04-24 10:59 UTC, Sorokin-Oleg commented on docs/guides/diagram_editor/editbar/complex_controls/lineshape.md
> +- `compact` - (optional) specifies the compact mode, removes indents and frame
@serhiipylypchuk1991 уберем из сервисных, определим выше

2024-04-24 10:59 UTC, Sorokin-Oleg commented on docs/guides/diagram_editor/editbar/complex_controls/lineshape.md
> +const editor= new dhx.DiagramEditor("editor", {
@serhiipylypchuk1991 editor_container

2024-04-24 10:59 UTC, Sorokin-Oleg commented on docs/guides/diagram_editor/editbar/complex_controls/pointerview.md
> +    compact?: boolean, // ??? by default
@serhiipylypchuk1991 уберем из сервисных, определим выше. False by default

2024-04-24 10:59 UTC, Sorokin-Oleg commented on docs/guides/diagram_editor/editbar/complex_controls/pointerview.md
> +- `compact` - (optional) specifies the compact mode, removes indents and frame
@serhiipylypchuk1991 уберем из сервисных, определим выше. False by default

2024-04-24 10:59 UTC, Sorokin-Oleg commented on docs/guides/diagram_editor/editbar/complex_controls/pointerview.md
> +- `padding` - (optional) sets the padding for the content inside the control group. *"8px"* by default
@serhiipylypchuk1991 "0 16px"

2024-04-24 10:59 UTC, Sorokin-Oleg commented on docs/guides/diagram_editor/editbar/complex_controls/pointerview.md
> +:::warning
@serhiipylypchuk1991 заметка выше

2024-04-24 10:59 UTC, Sorokin-Oleg commented on docs/guides/diagram_editor/editbar/complex_controls/pointerview.md
> +const editor= new dhx.DiagramEditor("editor", {
@serhiipylypchuk1991 editor_container

2024-04-24 10:59 UTC, Sorokin-Oleg commented on docs/guides/diagram_editor/editbar/complex_controls/position.md
> +    compact?: boolean, // ??? by default
@serhiipylypchuk1991 по аналогии выше

2024-04-24 10:59 UTC, Sorokin-Oleg commented on docs/guides/diagram_editor/editbar/complex_controls/position.md
> +- `padding` - (optional) sets the padding for the content inside the control group. *"8px"* by default
@serhiipylypchuk1991 по аналогии выше

2024-04-24 10:59 UTC, Sorokin-Oleg commented on docs/guides/diagram_editor/editbar/complex_controls/position.md
> +:::warning
@serhiipylypchuk1991 по аналогии выше

2024-04-24 10:59 UTC, Sorokin-Oleg commented on docs/guides/diagram_editor/editbar/complex_controls/position.md
> +- `compact` - (optional) specifies the compact mode, removes indents and frame
@serhiipylypchuk1991 по аналогии выше

2024-04-24 10:59 UTC, Sorokin-Oleg commented on docs/guides/diagram_editor/editbar/complex_controls/position.md
> +const editor= new dhx.DiagramEditor("editor", {
@serhiipylypchuk1991 по аналогии выше

2024-04-24 10:59 UTC, Sorokin-Oleg commented on docs/guides/diagram_editor/editbar/complex_controls/size.md
> +    compact?: boolean, // ??? by default
@serhiipylypchuk1991 по аналогии выше

2024-04-24 10:59 UTC, Sorokin-Oleg commented on docs/guides/diagram_editor/editbar/complex_controls/size.md
> +- `padding` - (optional) sets the padding for the content inside the control group. *"8px"* by default
@serhiipylypchuk1991 по аналогии выше

2024-04-24 10:59 UTC, Sorokin-Oleg commented on docs/guides/diagram_editor/editbar/complex_controls/size.md
> +:::warning
@serhiipylypchuk1991 по аналогии выше

2024-04-24 10:59 UTC, Sorokin-Oleg commented on docs/guides/diagram_editor/editbar/complex_controls/size.md
> +- `compact` - (optional) specifies the compact mode, removes indents and frame
@serhiipylypchuk1991 по аналогии выше

2024-04-24 10:59 UTC, Sorokin-Oleg commented on docs/guides/diagram_editor/editbar/complex_controls/size.md
> +const editor= new dhx.DiagramEditor("editor", {
@serhiipylypchuk1991 по аналогии выше

2024-04-24 10:59 UTC, Sorokin-Oleg commented on docs/guides/diagram_editor/editbar/complex_controls/textalign.md
> +    compact?: boolean, // ??? by default
@serhiipylypchuk1991 по аналогии выше

2024-04-24 10:59 UTC, Sorokin-Oleg commented on docs/guides/diagram_editor/editbar/complex_controls/textalign.md
> +- `padding` - (optional) sets the padding for the content inside the control group. *"8px"* by default
@serhiipylypchuk1991 по аналогии выше

2024-04-24 10:59 UTC, Sorokin-Oleg commented on docs/guides/diagram_editor/editbar/complex_controls/textalign.md
> +:::warning
@serhiipylypchuk1991 по аналогии выше

2024-04-24 10:59 UTC, Sorokin-Oleg commented on docs/guides/diagram_editor/editbar/complex_controls/textalign.md
> +- `compact` - (optional) specifies the compact mode, removes indents and frame
@serhiipylypchuk1991 по аналогии выше

2024-04-24 10:59 UTC, Sorokin-Oleg commented on docs/guides/diagram_editor/editbar/complex_controls/textalign.md
> +const editor= new dhx.DiagramEditor("editor", {
@serhiipylypchuk1991 по аналогии выше

2024-04-24 10:59 UTC, Sorokin-Oleg commented on docs/guides/diagram_editor/editbar/complex_controls/textstyle.md
> +    compact?: boolean, // ??? by default
@serhiipylypchuk1991 по аналогии выше

2024-04-24 10:59 UTC, Sorokin-Oleg commented on docs/guides/diagram_editor/editbar/complex_controls/textstyle.md
> +- `padding` - (optional) sets the padding for the content inside the control group. *"8px"* by default
@serhiipylypchuk1991 по аналогии выше

2024-04-24 10:59 UTC, Sorokin-Oleg commented on docs/guides/diagram_editor/editbar/complex_controls/textstyle.md
> +:::warning
@serhiipylypchuk1991 по аналогии выше

2024-04-24 10:59 UTC, Sorokin-Oleg commented on docs/guides/diagram_editor/editbar/complex_controls/textstyle.md
> +- `compact` - (optional) specifies the compact mode, removes indents and frame
@serhiipylypchuk1991 по аналогии выше

2024-04-24 10:59 UTC, Sorokin-Oleg commented on docs/guides/diagram_editor/editbar/complex_controls/textstyle.md
> +const editor= new dhx.DiagramEditor("editor", {
@serhiipylypchuk1991 по аналогии выше

2024-04-25 07:44 UTC, Sorokin-Oleg requested changes

2024-04-25 07:44 UTC, Sorokin-Oleg commented on docs/guides/diagram_editor/editbar/complex_controls/arrange.md
> +:::warning
@serhiipylypchuk1991 мы это предупреждение отобразим в свойствах controls, properties и в гайде. Давай в комплексных везде уберем.

2024-04-25 07:58 UTC, Sorokin-Oleg approved these changes

2024-04-26 09:00 UTC, mafanya23 commented on docs/guides/diagram_editor/editbar/complex_controls/arrange.md
> +**Change log**: The control was added in v6.0
А нам точно нужен change log на страницах контролов?

2024-04-26 09:02 UTC, mafanya23 commented on docs/guides/diagram_editor/editbar/complex_controls/arrange.md
> +The **Arrange** control is available only in the *default* mode of the Diagram editor. The control is not available for **line** and **lineTitle** elements.
я бы добавила the для **line** and **lineTitle** elements

2024-04-26 09:07 UTC, mafanya23 commented on docs/guides/diagram_editor/editbar/complex_controls/headercommon.md
> +@short: The complex control for for changing visibility, color, and height of the group header
одно for лишнее)

2024-04-26 09:09 UTC, mafanya23 commented on docs/guides/diagram_editor/editbar/complex_controls/headerposition.md
> +@short: The complex control for changing position of the group header
the position

2024-04-26 09:10 UTC, mafanya23 commented on docs/guides/diagram_editor/editbar/complex_controls/border.md
> +@short: The complex control for displaying and modifying borders of a Diagram element
the borders

2024-04-26 09:11 UTC, mafanya23 commented on docs/guides/diagram_editor/editbar/complex_controls/headercommon.md
> +The **Header common** control is available only for **group** and **swimlane** elements in the *default* mode of the Diagram editor.
the **group** and **swimlane** elements

2024-04-26 09:13 UTC, mafanya23 commented on docs/guides/diagram_editor/editbar/complex_controls/headerposition.md
> +:::
the **group** and **swimlane** elements

2024-04-26 09:19 UTC, mafanya23 commented on docs/guides/diagram_editor/editbar/complex_controls/arrange.md
> +description: You can explore the Arrange control of Editbar in the documentation of the the DHTMLX JavaScript Diagram library. Browse developer guides and API reference, try out code examples and liv
Здесь и в других контролах, лишнее the в "the DHTMLX JavaScript Diagram library". В базовых тоже подправлю

2024-04-26 09:21 UTC, mafanya23 commented on docs/guides/diagram_editor/editbar/complex_controls/position.md
> +@short: The complex control for configuring the shape offset from the predefined algorithm on the X and Y axe
axes

2024-04-26 09:29 UTC, mafanya23 commented on docs/guides/diagram_editor/editbar/complex_controls/pointerview.md
> +- `$properties` - (optional) allows you to override values of [basic controls](TODO) within a complex control. You can configure the following element of the **Pointer view** control based on the bas
the following elements

2024-04-26 09:29 UTC, mafanya23 commented on docs/guides/diagram_editor/editbar/complex_controls/position.md
> +- `$properties` - (optional) allows you to override values of [basic controls](TODO) within a complex control. You can configure the following element of the **Position** control based on the basic c
the following elements

2024-04-26 09:29 UTC, mafanya23 commented on docs/guides/diagram_editor/editbar/complex_controls/size.md
> +- `$properties` - (optional) allows you to override values of [basic controls](TODO) within a complex control. You can configure the following element of the **Size** control based on the basic contr
the following elements

2024-04-26 09:30 UTC, mafanya23 commented on docs/guides/diagram_editor/editbar/complex_controls/textalign.md
> +- `$properties` - (optional) allows you to override values of [basic controls](TODO) within a complex control. You can configure the following element of the **Text align** control based on the basic
the following elements

2024-04-26 09:30 UTC, mafanya23 commented on docs/guides/diagram_editor/editbar/complex_controls/textstyle.md
> +- `$properties` - (optional) allows you to override values of [basic controls](TODO) within a complex control. You can configure the following element of the **Text style** control based on the basic
the following elements

2024-04-30 07:51 UTC, Sorokin-Oleg commented
@serhiipylypchuk1991 @mafanya23 нужно согласовать масштаб изображений, в комплексных, как мне кажется, масштаб сильно завышен. И если мы делаем скрин контрола, то область вокруг, будет также полезна. Изображение как пример 
![image](https://github.com/DHTMLX/docs-diagram/assets/42112911/115eff02-f84b-4ba0-9f92-5fab26e9b39d)

2024-04-30 07:55 UTC, Sorokin-Oleg commented
Про масштабы, так сейчас выглядит одна из страниц в комплексных контролах 
![image](https://github.com/DHTMLX/docs-diagram/assets/42112911/9a904517-e62f-42c8-b0c7-dfe9239713c5)

2024-04-30 20:23 UTC, merged