Update the magnetic property
DHTMLX/docs-diagram pull request #4
Opened 2023-11-21 07:42 UTC by serhiipylypchuk1991

2023-11-22 10:41 UTC, Sorokin-Oleg requested changes

2023-11-22 10:41 UTC, Sorokin-Oleg commented on docs/api/diagram_editor/editor/config/magnetic_property.md
> +~~~js{3-7}
@serhiipylypchuk1991 тут видимо что-то не сработало, подсветка синтаксиса стала серой для всего примера

2023-11-23 08:05 UTC, mafanya23 approved these changes

2023-11-23 08:14 UTC, Sorokin-Oleg approved these changes

2023-11-23 10:22 UTC, merged