Diagram Editor. Add the grid property
DHTMLX/docs-diagram pull request #5
Opened 2023-11-21 12:15 UTC by serhiipylypchuk1991

2023-11-22 10:29 UTC, Sorokin-Oleg requested changes

2023-11-22 10:29 UTC, Sorokin-Oleg commented on docs/api/diagram_editor/editor/config/grid_property.md
> +# gridStep
@serhiipylypchuk1991 Думаю, тут должно быть что-то друго

2023-11-23 08:07 UTC, mafanya23 approved these changes

2023-11-23 08:13 UTC, Sorokin-Oleg approved these changes

2023-11-23 10:21 UTC, merged