Diagram Editor. Add the resizePoints property
DHTMLX/docs-diagram pull request #6
Opened 2023-11-22 10:41 UTC by serhiipylypchuk1991

2023-11-22 10:51 UTC, Sorokin-Oleg requested changes

2023-11-22 10:51 UTC, Sorokin-Oleg commented on docs/api/diagram_editor/editor/config/resizepoints_property.md
> +~~~js{}
@serhiipylypchuk1991 `~~~js{}` тут ведь должен был быть диапазон? Отображается без подсветки синтаксиса

2023-11-23 08:09 UTC, mafanya23 approved these changes

2023-11-23 08:09 UTC, Sorokin-Oleg approved these changes

2023-11-23 10:21 UTC, merged