Diagram Editor. Add the connectionPoints property
DHTMLX/docs-diagram pull request #7
Opened 2023-11-24 06:50 UTC by serhiipylypchuk1991

2023-11-24 09:20 UTC, mafanya23 commented on docs/api/diagram_editor/editor/config/connectionpoints_property.md
> +The `connectionPoints` property works only if `type: "default"`.
Suggestion: The `connectionPoints` property works only if the 'type:default' configuration option is specified.

2023-11-27 07:43 UTC, Sorokin-Oleg requested changes

2023-11-27 07:43 UTC, Sorokin-Oleg commented on docs/api/diagram_editor/editor/config/connectionpoints_property.md
> +The `connectionPoints` property works only if the `type: "default"` configuration is specified.
@serhiipylypchuk1991 @mafanya23 тут все куда проще. Свойство работает только в `default` mode.
При этом в диаграммах, если не указан тип, то он установлен в дефолтный режим, фраза уже звучит не корректно в такой формулировке.

2023-11-28 08:09 UTC, mafanya23 approved these changes

2023-11-28 11:44 UTC, Sorokin-Oleg approved these changes

2023-11-29 18:12 UTC, merged