Diagram Editor. Add View property and related API
DHTMLX/docs-diagram pull request #9
Opened 2023-12-01 09:24 UTC by serhiipylypchuk1991

2023-12-05 09:58 UTC, Sorokin-Oleg requested changes

2023-12-05 09:58 UTC, Sorokin-Oleg commented on docs/api/diagram_editor/editor/config/view_property.md
> +const editor = new dhx.DiagramEditor("editor_container", {
@serhiipylypchuk1991 я бы все же показал тут пример приведенный в описании к задаче. Он более информативен. Пользователь должен представлять, что можно ожидать от свойства `view`. В данный момент все ограничивается булевыми значениями, которые являются довольно очевидными.
```
const editor = new dhx.DiagramEditor("editor", {
    type: "default",
    view: {
        toolbar: {
            css: "toolbar_custom",
            data: ["file", "separator", "scale"],
        },
        shapebar: {
            width: 400,
        },
        editbar: false,
    }
});
```
 При этом `type: "default"` нужно оставить, так как такая конфигурация возможна только в данном типе диаграмм.

2023-12-05 09:58 UTC, Sorokin-Oleg commented on docs/api/diagram_editor/view/methods/isvisible_method.md
> +editor.view.isVisible("shapebar"); // --> false
@serhiipylypchuk1991 Такая запись `// --> false`, почему-то, некорректно отображается, можно заменить на `// return false`

2023-12-05 09:58 UTC, Sorokin-Oleg commented on docs/api/diagram_editor/view/methods/isvisible_method.md
> +editor.view.isVisible("shapebar"); // --> false
![image](https://github.com/DHTMLX/docs-diagram/assets/42112911/5ed8e977-6eaf-4b42-9a57-7d53e383949e)

2023-12-05 09:58 UTC, Sorokin-Oleg commented on docs/api/diagram_editor/view/events/afterhide_event.md
> +"afterHide": (view: string) => boolean | void;
@serhiipylypchuk1991
`"afterHide": (view: string) => void;`
or
`"afterHide": (view: "toolbar" | "shapebar" | "editbar") => void;`

2023-12-05 09:58 UTC, Sorokin-Oleg commented on docs/api/diagram_editor/view/events/afterhide_event.md
> +- `view` - (required) a view that was hidden. Refer to the [`view`](api/diagram_editor/editor/config/view_property.md) property for details.
@serhiipylypchuk1991 тут ремарка, на всякий случай. Конфигурация компонента при инициализации не триггерит события.

2023-12-05 09:58 UTC, Sorokin-Oleg commented on docs/api/diagram_editor/view/events/aftershow_event.md
> +"afterShow": (view: string) => boolean | void;
@serhiipylypchuk1991
`"afterShow": (view: string) => void;`
or
`"afterShow": (view: "toolbar" | "shapebar" | "editbar") => void;`

2023-12-05 09:58 UTC, Sorokin-Oleg commented on docs/api/diagram_editor/view/events/beforehide_event.md
> +        shapebar: false,
@serhiipylypchuk1991  в этом примере лучше `true` установить

2023-12-05 09:58 UTC, Sorokin-Oleg commented on docs/api/diagram_editor/view/events/afterhide_event.md
> +        shapebar: false,
@serhiipylypchuk1991  в этом примере лучше `true` установить

2023-12-08 08:11 UTC, Sorokin-Oleg commented on docs/api/diagram_editor/view/events/afterhide_event.md
> +- `view` - (required) a view that was hidden. Refer to the [`view`](api/diagram_editor/editor/config/view_property.md) property for details.
@serhiipylypchuk1991 оно для всех. Но это не пишем. Это я для тебя написал, чтобы было понимание. Просто увидел пример, и решил написать. Так как если в конфиге установить `shapebar: false`, или тип того, то редактор промолчит и не будет дергать события так как эти действия были описаны при инициализации. Сработают если юзать метод или через ui. Но это для всего так.

2023-12-08 08:55 UTC, Sorokin-Oleg requested changes

2023-12-08 08:55 UTC, Sorokin-Oleg commented on docs/api/diagram_editor/view/events/afterhide_event.md
> +- `view` - (required) a view that was hidden. Refer to the [`view`](api/diagram_editor/editor/config/view_property.md) property for details. The component configuration doesn't trigger events when in
@serhiipylypchuk1991 
Не, это не нужно писать :)
> The component configuration doesn't trigger events when initializing.

2023-12-08 08:55 UTC, Sorokin-Oleg commented on docs/api/diagram_editor/view/events/beforehide_event.md
> +"beforeHide": (view: "toolbar" | "shapebar" | "editbar") => void;
@serhiipylypchuk1991 хех)) Ну почти, только вот так. Там где `before` мы можем прервать событие, то есть вернуть `boolean` значение, либо ничего не возвращать.
```
(view: "toolbar" | "shapebar" | "editbar") => boolean | void;
```

2023-12-08 08:55 UTC, Sorokin-Oleg commented on docs/api/diagram_editor/editor/config/view_property.md
> +    type: "default", // required
@serhiipylypchuk1991 можно `required` не писать, если тип не укажем подтянется `default` режим. Просто хотелось бы его в примере оставить, чтобы была явная инициализация типа.

2023-12-08 09:45 UTC, Sorokin-Oleg approved these changes

2023-12-08 09:47 UTC, mafanya23 approved these changes

2023-12-08 09:49 UTC, merged